### ISSUE TITLE
Feature request feasibility

### ISSUE THREAD

**Issue by pleasehelpcoax** [err4o4/spotify-car-thing-reverse-engineering#19]
Hello!

As we go forward experimenting with the newly unlocked hardware, Woot Woot! (I'm very excited to see what comes of it), I was wondering if the following features were even possible:

-Google Maps navigation displayed on car thing

-Ability to accept calls with an android device

**Comment by patrickjquinn** [comment]
This probably isn't the right place for this, suggest you keep this repo to the reverse engineering efforts and not basic feature requests that might one day be handled by open auto or another project.
